Make it work with ActiveSupport::Cache::RedisCacheStore (from rails) instead of just with ActiveSupport::Cache::RedisStore (from redis-rails)
Resolves error: undefined method `keys' for #<Rack::Attack::StoreProxy::RedisCacheStoreProxy>