Make it work when Rack::Attack.cache.store is set to an instance of ActiveSupport::Cache::RedisCacheStore (from rails)
Before it was only tested with cache.store set to an instance of Redis::Store from redis-store gem.
(Used by ActiveSupport::Cache::RedisStore (from redis-activesupport gem))

Resolves error: undefined method `keys' for #<Rack::Attack::StoreProxy::RedisCacheStoreProxy>

It is still recommended to use Redis::Store though, especially if using a namespace, because its
`keys` method automatically strips out the namespace, whereas when Redis#keys (used by
ActiveSupport::Cache::RedisCacheStore) does not.